---
title: "plotting_code"
output: html_document
date: "2025-04-22"
---

```{r setup, include=FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("rtidyverse")
library(tidyverse)
library(readr)
library(ggpattern)
```



```{r}
sharpe_ppf_resultsR <- read_csv("./sharpe_csvs_to_plot/sharpe_ppf_results.csv")
sharpe_ppf_resultsR <- sharpe_ppf_resultsR %>%
  group_by(CS, DACS) %>%
  mutate(freq = n()) %>%
  ungroup()
p1 <- ggplot(sharpe_ppf_resultsR, aes(x = CS, y = DACS,size=freq)) +
  geom_point(alpha = 0.6) +
  scale_size_continuous(
    range = c(2, 10),
    breaks = sort(unique(sharpe_ppf_resultsR$freq))
  ) +
  geom_abline(slope = 1, intercept = 0, color = "red") +
  theme_bw() +
  ggtitle("Sharpe ratio")+
  theme(plot.title = element_text(hjust = 0.5,vjust=0,size = 16),
        axis.title = element_text(size = 16),  # Increase axis title size
    axis.text = element_text(size = 13),   # Increase axis label size
    legend.title = element_text(size = 16),  # Increase legend title size
    legend.text = element_text(size = 16),
    strip.text = element_text(size = 16))
p1 <- p1 +
  theme(legend.position = "bottom") +
  guides(
    size = guide_legend(order = 1)    # freq
  )
# sharpe_tradeoff_resultsR <- read_csv("./sharpe_csvs_to_plot/sharpe_tradeoff_results.csv")
#  ggplot(sharpe_tradeoff_resultsR, aes(x = `% decrease in #R`, y = `% decrease in similarity`)) +
#   geom_point() +
#   facet_grid(`alpha` ~ `Setting`) +
#   theme_bw()+
#   # theme(aspect.ratio = 10/13)+
#   ggtitle("Sharpe ratio")+
#   theme(plot.title = element_text(hjust = 0.5,vjust=0,size = 16),
#         axis.title = element_text(size = 16),  # Increase axis title size
#     axis.text = element_text(size = 16),   # Increase axis label size
#     legend.title = element_text(size = 16),  # Increase legend title size
#     legend.text = element_text(size = 16),
#     strip.text = element_text(size = 16))

markowitz_ppf_resultsR <- read_csv("./markowitz_csvs_to_plot/markowitz_ppf_results.csv")
markowitz_ppf_resultsR <- markowitz_ppf_resultsR %>%
  group_by(CS, DACS, gamma) %>%
  mutate(freq = n()) %>%
  ungroup()
p2 <- ggplot(markowitz_ppf_resultsR, aes(x = CS, y = DACS, size=freq)) +
  geom_point(alpha = 0.6) +
  scale_size_continuous(
    range = c(2, 10),
    breaks = c(1, 45, 80, 136)#sort(unique(markowitz_ppf_resultsR$freq))
  ) +
  geom_abline(slope = 1, intercept = 0, color = "red") +
  facet_grid(~ `gamma`, scales = "free_x") +
  theme_bw()+
  ggtitle("Markowitz objective")+
  theme(plot.title = element_text(hjust = 0.5,vjust=0,size = 16),
        axis.title = element_text(size = 16),  # Increase axis title size
    axis.text = element_text(size = 13),   # Increase axis label size
    legend.title = element_text(size = 16),  # Increase legend title size
    legend.text = element_text(size = 16),
    strip.text = element_text(size = 16))

# markowitz_tradeoff_resultsR <- read_csv("./markowitz_csvs_to_plot/markowitz_tradeoff_results.csv")
# # #markowitz_ppf_resultsR <- markowitz_ppf_resultsR[markowitz_ppf_resultsR$gamma != "gamma=0.25",]
# ggplot(markowitz_tradeoff_resultsR, aes(x = `% decrease in #R`, y = `% decrease in similarity`, color=gamma)) +
#   geom_point() +
#   #facet_wrap(~ alpha + Setting, scales = "free") +
#   facet_grid(`alpha` ~ `Setting`, scale = "free") +
#   theme_bw()+
#   # theme(aspect.ratio = 10/13)+
#   ggtitle("Markowitz objective")+
#   theme(plot.title = element_text(hjust = 0.5,vjust=0,size = 16),
#         axis.title = element_text(size = 16),  # Increase axis title size
#     axis.text = element_text(size = 16),   # Increase axis label size
#     legend.title = element_text(size = 16),  # Increase legend title size
#     legend.text = element_text(size = 16),
#     strip.text = element_text(size = 16))

# combined_plot <- p1 + plot_spacer()+ p2 +
#   #plot_layout(ncol = 2, widths = c(1, 1))
#   plot_layout(ncol = 3, widths = c(1, 0.1, 1))
# Remove legend from p2
# p2_clean <- p2 + theme(legend.position = "none")
p2_clean <- p2 +
  theme(legend.position = "bottom") +
  guides(
    color = guide_legend(order = 1),  # gamma
    size = guide_legend(order = 2)    # freq
  )

# Combine without legend
# combined_plot <- p1 + p2_clean + plot_layout(ncol = 2, widths = c(1, 1))
# combined_plot <- grid.arrange(p1, p2, ncol=2)
#combined_plot <- (p1 + p2_clean) + plot_layout(ncol = 2) & theme(legend.position = "bottom", legend.box = "vertical")
combined_plot <- (p1 + p2_clean) + 
  plot_layout(ncol = 2, widths = c(0.8, 1.2)) & 
  theme(legend.position = "bottom", legend.box = "vertical")


# Print the final layout
combined_plot
ggsave("combined_sharpe-markowitz.pdf", combined_plot, width = 16, height = 8)

```


```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(patchwork)  # needed for combining plots with `+` and `plot_layout`

# Read in the data
sharpe_mt_resultsR <- read_csv("./sharpe_csvs_to_plot/sharpe_mt_metric_results.csv")
markowitz_mt_resultsR <- read_csv("./markowitz_csvs_to_plot/markowitz_mt_metric_results.csv")

# Create the Sharpe plot
p1 <- ggplot(sharpe_mt_resultsR, aes(x = error_metric, y = rate, fill = method)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_errorbar(
    aes(ymin = rate - 1.96*serr, ymax = rate + 1.96*serr),
    position = position_dodge(width = 0.9),
    width = 0.25
  ) +
  geom_hline(yintercept = 0.5, linetype = "dashed", color = "black") +
  theme_bw() +
  ggtitle("Sharpe ratio") +
  theme(
    axis.title.x = element_blank(),
    axis.ticks.x = element_blank(),
    plot.title = element_text(hjust = 0.5, vjust = 0, size = 16),
    axis.title = element_text(size = 16),
    axis.text = element_text(size = 16),
    legend.title = element_text(size = 16),
    legend.text = element_text(size = 16),
    strip.text = element_text(size = 16)
  )

# Create the Markowitz plot
p2 <- ggplot(markowitz_mt_resultsR, aes(x = error_metric, y = rate, fill = method)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_errorbar(
    aes(ymin = rate - 1.96*serr, ymax = rate + 1.96*serr),
    position = position_dodge(width = 0.9),
    width = 0.25
  ) +
  geom_hline(yintercept = 0.5, linetype = "dashed", color = "black") +
  facet_grid(~ gamma, scales = "free_x") +
  theme_bw() +
  ggtitle("Markowitz objective") +
  theme(
    axis.title.x = element_blank(),
    axis.ticks.x = element_blank(),
    plot.title = element_text(hjust = 0.5, vjust = 0, size = 16),
    axis.title = element_text(size = 16),
    axis.text = element_text(size = 16),
    legend.title = element_text(size = 16),
    legend.text = element_text(size = 16),
    strip.text = element_text(size = 16)
  )

# Adjust legend position
p2_clean <- p2 + theme(legend.position = "bottom")

# Combine plots
combined_fdr_power_plot <- (p1 + p2_clean) + 
  plot_layout(ncol = 2) & 
  theme(legend.position = "bottom", legend.box = "vertical")

# Save to file
ggsave("combined_sharpe-markowitz_fdr_power.pdf", combined_fdr_power_plot, width = 16, height = 8)

```



```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(patchwork)  # needed for combining plots with `+` and `plot_layout`

# Read in the data
sharpe_mt_resultsR <- read_csv("./sharpe_csvs_to_plot/sharpe_mt_numr_results.csv")
markowitz_mt_resultsR <- read_csv("./markowitz_csvs_to_plot/markowitz_mt_numr_results.csv")

# Create the Sharpe plot
p1 <- ggplot(sharpe_mt_resultsR, aes(x = num_rejections, y = `#R`, fill = method)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_errorbar(
    aes(ymin = `#R` - 1.96*serr, ymax = `#R` + 1.96*serr),
    position = position_dodge(width = 0.9),
    width = 0.25
  ) +
  theme_bw() +
  ggtitle("Sharpe ratio") +
  theme(
    axis.title.x = element_blank(),
    axis.ticks.x = element_blank(),
    plot.title = element_text(hjust = 0.5, vjust = 0, size = 16),
    axis.title = element_text(size = 16),
    axis.text = element_text(size = 16),
    legend.title = element_text(size = 16),
    legend.text = element_text(size = 16),
    strip.text = element_text(size = 16)
  )

# Create the Markowitz plot
p2 <- ggplot(markowitz_mt_resultsR, aes(x = num_rejections, y = `#R`, fill = method)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_errorbar(
    aes(ymin = `#R` - 1.96*serr, ymax = `#R` + 1.96*serr),
    position = position_dodge(width = 0.9),
    width = 0.25
  ) +
  facet_grid(~ gamma, scales = "free_x") +
  theme_bw() +
  ggtitle("Markowitz objective") +
  theme(
    axis.title.x = element_blank(),
    axis.ticks.x = element_blank(),
    plot.title = element_text(hjust = 0.5, vjust = 0, size = 16),
    axis.title = element_text(size = 16),
    axis.text = element_text(size = 16),
    legend.title = element_text(size = 16),
    legend.text = element_text(size = 16),
    strip.text = element_text(size = 16)
  )

# Adjust legend position
p2_clean <- p2 + theme(legend.position = "bottom")

# Combine plots
combined_numr_plot <- (p1 + p2_clean) + 
  plot_layout(ncol = 2) & 
  theme(legend.position = "bottom", legend.box = "vertical")

# Save to file
ggsave("combined_sharpe-markowitz_numr.pdf", combined_numr_plot, width = 16, height = 8)


```


```{r}
sharpe_time_resultsR <- read_csv("./sharpe_csvs_to_plot/sharpe_time_results.csv")

p1 <- ggplot(sharpe_time_resultsR, aes(x = time, y = `Time (sec)`)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_errorbar(
    aes(ymin = `Time (sec)` - 1.96*serr, ymax = `Time (sec)` + 1.96*serr),
    position = position_dodge(width = 0.9),
    width = 0.25
  ) +
  theme_bw() +
  ggtitle("Sharpe ratio") + 
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    plot.title = element_text(hjust = 0.5,vjust=0,size = 16),
        axis.title = element_text(size = 16),  # Increase axis title size
    axis.text = element_text(size = 13),   # Increase axis label size
    legend.title = element_text(size = 16),  # Increase legend title size
    legend.text = element_text(size = 16),
    strip.text = element_text(size = 16)
  )


markowitz_time_resultsR <- read_csv("./markowitz_csvs_to_plot/markowitz_time_results.csv")

p2 <- ggplot(markowitz_time_resultsR, aes(x = time, y = `Time (sec)`, fill=gamma)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_errorbar(
    aes(ymin = `Time (sec)` - 1.96*serr, ymax = `Time (sec)` + 1.96*serr),
    position = position_dodge(width = 0.9),
    width = 0.25
  ) +
  theme_bw() +
  ggtitle("Markowitz objective") + 
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    plot.title = element_text(hjust = 0.5,vjust=0,size = 16),
      axis.title = element_text(size = 16),  # Increase axis title size
    axis.text = element_text(size = 13),   # Increase axis label size
    legend.title = element_text(size = 16),  # Increase legend title size
    legend.text = element_text(size = 16),
    strip.text = element_text(size = 16)
  )

p2_clean <- p2 +
  theme(legend.position = "bottom")

combined_time_plot <- (p1 + p2_clean) + plot_layout(ncol = 2) & theme(legend.position = "bottom", legend.box = "vertical")

ggsave("combined_time_sharpe-markowitz.pdf", combined_time_plot, width = 14, height = 8)
```




```{r}

sharpe_mt_resultsR <- read_csv("./sharpe_csvs_to_plot/sharpe_mt_metric_results.csv")
#markowitz_mt_resultsR <- markowitz_mt_resultsR %>% mutate(method_gamma = interaction(method, gamma, sep = "_"))

#markowitz_mt_resultsR <- merge(markowitz_mt_resultsR, Lines_in_plot, by = "alpha")
p1 <- ggplot(sharpe_mt_resultsR, aes(x = error_metric, y = rate, fill = method)) +
  # geom_bar_pattern(stat = "identity", position = "dodge", 
  #                  pattern_density = 0.1, 
  #                  pattern = "stripe",  # Change this to the pattern you want, like "stripe", "circle", etc.
  #                  color = "black") +
  geom_bar(stat = "identity", position = "dodge") +
  geom_errorbar(
    aes(ymin = rate - 1.96*serr, ymax = rate + 1.96*serr),
    position = position_dodge(width = 0.9),
    width = 0.25
  ) +
  geom_hline(yintercept = 0.5, linetype = "dashed", color = "black")+
  #facet_grid( ~ `gamma`, scales = "free_x") +
  theme_bw()+
  ggtitle("Sharpe ratio")+
  theme(axis.title.x = element_blank(),
    #axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    plot.title = element_text(hjust = 0.5,vjust=0,size = 16),
        axis.title = element_text(size = 16),  # Increase axis title size
    axis.text = element_text(size = 16),   # Increase axis label size
    legend.title = element_text(size = 16),  # Increase legend title size
    legend.text = element_text(size = 16),
    strip.text = element_text(size = 16))


markowitz_mt_resultsR <- read_csv("./markowitz_csvs_to_plot/markowitz_mt_metric_results.csv")
#markowitz_mt_resultsR <- markowitz_mt_resultsR %>% mutate(method_gamma = interaction(method, gamma, sep = "_"))

#markowitz_mt_resultsR <- merge(markowitz_mt_resultsR, Lines_in_plot, by = "alpha")
p2 <- ggplot(markowitz_mt_resultsR, aes(x = error_metric, y = rate, fill = method)) +
  # geom_bar_pattern(stat = "identity", position = "dodge", 
  #                  pattern_density = 0.1, 
  #                  pattern = "stripe",  # Change this to the pattern you want, like "stripe", "circle", etc.
  #                  color = "black") +
  geom_bar(stat = "identity", position = "dodge") +
  geom_errorbar(
    aes(ymin = rate - 1.96*serr, ymax = rate + 1.96*serr),
    position = position_dodge(width = 0.9),
    width = 0.25
  ) +
  geom_hline(yintercept = 0.5, linetype = "dashed", color = "black")+
  facet_grid( ~ `gamma`, scales = "free_x") +
  theme_bw()+
  ggtitle("Markowitz objective")+
  theme(axis.title.x = element_blank(),
    #axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    plot.title = element_text(hjust = 0.5,vjust=0,size = 16),
        axis.title = element_text(size = 16),  # Increase axis title size
    axis.text = element_text(size = 16),   # Increase axis label size
    legend.title = element_text(size = 16),  # Increase legend title size
    legend.text = element_text(size = 16),
    strip.text = element_text(size = 16))


p2_clean <- p2 +
  theme(legend.position = "bottom")

combined_fdr_power_plot <- (p1 + p2_clean) + plot_layout(ncol = 2) & theme(legend.position = "bottom", legend.box = "vertical")
ggsave("combined_sharpe-markowitz_fdr_power.pdf", combined_fdr_power_plot, width = 16, height = 8)
```

